// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Title       string  `json:"Title"`
	Content     string  `json:"Content"`
	Author      *string `json:"Author"`
	Hero        *string `json:"Hero"`
	PublishedAt *string `json:"Published_At"`
	UpdatedAt   *string `json:"Updated_At"`
}

type Post struct {
	ID          int    `json:"id"`
	Title       string `json:"Title"`
	Content     string `json:"Content"`
	Author      string `json:"Author"`
	Hero        string `json:"Hero"`
	PublishedAt string `json:"Published_At"`
	UpdatedAt   string `json:"Updated_At"`
}
